### ISSUE TITLE
Lien "en savoir plus" cassé

### ISSUE THREAD

**Issue by mendoc** [Steeven1995/cv-tech-ecole241#6]
Lorsqu'on clique sur le lien "en savoir plus" des cards, ça ne même nulle part.
Il manque apparemment les ":" dans les adresses.
Au lieu de https:// c'est plutôt http//

**Comment by Steeven1995** [comment]
Hello coach merci pour ton retour!

Le sam. 22 oct. 2022 à 10:19, Dimitri ONGOUA ***@***.***> a
écrit :
